# Generated by Django 3.2.4 on 2021-06-15 12:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
        migrations.AddField(
            model_name='company',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.educationlevel'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='minimum_education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.educationlevel'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='salary_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.salaryrange'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='desired_salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.salaryrange'),
        ),
    ]
