# Generated by Django 3.2.4 on 2021-06-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRange',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='salary_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.salaryrange'),
        ),
    ]
