# Generated by Django 3.2.4 on 2021-06-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_alter_salaryrange_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.educationlevel'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='minimum_education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.educationlevel'),
        ),
    ]
