# Generated by Django 3.2.4 on 2021-06-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_auto_20210613_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='desired_salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.salaryrange'),
        ),
    ]
